name: download-promax
#自动更新trcker版本----最大16G
on:
  #gollum
  workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
          retain_days: 2
          keep_minimum_runs: 6
    - name: downloads
      run: |
        cd ~/
        mkdir -p ~/downloads
    - name: RUN
      run: |
        mv app.py run.py
        mv requirements.txt requirement.txt
        chmod -R 777 run.py
        chmod -R 777 requirement.txt
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: RUN
      run: |
        python run.py
        



        
 
